### Sampling Distributions

In order to gain a bit more comfort with this idea of sampling distributions, let's do some practice in python.

Below is an array that represents the some people, where 0 represents the people who are Vegetarian, and 1 represents the people that are not vegetarian.

In [26]:
import numpy as np
np.random.seed(42)

people = np.array([1,0,1,1,1,1,0,0,0,0,1,1,0,1,0,1,1,1,0,1,1,0,1,1,0,0,1,1,0,1])

`1.` Find the proportion of people who are vegetarian in the above array.

In [27]:
people.mean()

0.59999999999999998

`2.` Use numpy's **random.choice** to simulate 5 draws from the `people` array.  What is proportion of your sample are NOT vegetarian?

In [28]:
sample = np.random.choice(people, 5)
sample.mean()

0.40000000000000002

`3.` Repeat the above to obtain 10,000 additional proportions, where each sample was of size 5.  Store these in a variable called `sample_props`.

In [38]:
sample_props = np.random.random_sample((10000,5))
print(sample_props)

[[ 0.16118464  0.94866745  0.13468769  0.83535177  0.54040681]
 [ 0.11401231  0.91950371  0.92810498  0.61536151  0.38886004]
 [ 0.60749878  0.62776014  0.62213826  0.7334083   0.06714445]
 ..., 
 [ 0.81010145  0.01212805  0.42645611  0.08423713  0.36838867]
 [ 0.81018404  0.1500606   0.35173272  0.25533917  0.13002424]
 [ 0.96916618  0.43416932  0.02180724  0.67753719  0.52487864]]


`4.` What is the mean proportion of all 10,000 of these proportions?  This is often called **the mean of the sampling distribution**.

In [39]:
np.mean(sample_props)

0.50141930734061835

`5.` What are the variance and standard deviation for the original 30 data values?

In [42]:
var1 = np.var(people)
std1 = np.std(people)
print('The variance for the original data is: ' + str(var1))
print("The standard deviation for the original data is: " + str(std1))

The variance for the original data is: 0.24
The standard deviation for the original data is: 0.489897948557


`6.` What are the variance and standard deviation for the 10,000 proportions you created?

In [43]:
var2 = np.var(sample_props)
std2 = np.std(sample_props)
print('The variance for the 10,000 proportions is: ' + str(var2))
print("The standard deviation for the 10,000 proportions is: " + str(std2))

The variance for the 10,000 proportions is: 0.0834276019285
The standard deviation for the 10,000 proportions is: 0.288838366441


`7.` Compute p(1-p), which of your answers does this most closely match?

`8.` Compute p(1-p)/n, which of your answers does this most closely match?